### ISSUE TITLE
.svg file seems to be missing?

### ISSUE THREAD

**Issue by taste-media** [absolunet/frontend-resources#1]
Hi,

I'm trying to grt this svg file but am unable to download it. Please can you advise?

I've managed to get the ttf, woff and eof files

Any assistance greatly appreciated, thank you

**Comment by jblandry** [comment]
Which svg file?

**Comment by taste-media** [comment]
Apologies, it's the MuseoSans 500 file

**Comment by jblandry** [comment]
This link seems to work for me : https://raw.githubusercontent.com/absolunet/frontend-resources/master/fonts/MuseoSans/museosans_500-webfont.svg
